language: java

install: ./gradlew setupCiWorkspace

script: ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew artifactoryPublish
  on:
    branch: 1.10.2

jdk:
  - oraclejdk8

env:
  global:
    - secure: SYWSC2F2JnZqt+A2jVFMjtVATWpGV6LrlxwkPK0TZxpyBKSrWkQp9m9nItMGwP8gtnqY6Z+WDYsduO1/1N4l74PRrgDYAApLk9ig3nyVtI2BO1xo4NzPBNyd2Yd3h0HT8qVjB2gO75pNm2iBN7dM4lArdoETN153lDgK9yg+/9Fe/Y5v0oUP43TAEByCvOV5DmigRse5MrtIoUZ9aCTo2OMb5CZenQBLDbviru1fsz8sDvIwbO1yhrzb5W69pQpo2JP5s5YEkvG1IvWIrXHXUKPhaS9MnWhjntZsM9zB0qlqJvYRcY9AGxIkXFQuSrnMjgCQKRcWWybTwxsJmKWmsK3E0PPguQcf+E1FJ9mt0Lr7KMxdPuXfOTpjtIdh4LqNQCTBZXruMp4TS6zgxAR4DO5BCxvrJC+QICg+4B7NR5uUt+fUFti5L6/Kv5eTz2RoFsC+/a7dn5XOS4oAD0n4+XhDk1ggtyZAzK4Smw+P+3EMfFHcGJ5oeRUVH1fGrtP4zqJiqBgGoyRBLLHRi+rXhfofEqN20Uhj3bjXrLiSRrbTqHOVpUTs2vJzQfe9iGqbjsSAR7nTdryiP4GxbQ3eMS0XcPSWThvCgwquJDIT0g4ykyjO/I/EWGAPubE83J3w5x+MxR/qU5sQo7+h/xVszVPA4xyZQn2CeXcak+/UqNU=
    - secure: Vh11DcLTpNgRPOTSyfgoJivZqO+/eHjDuEur81Uhn9jvIkU20n4YbHWvi224h3pZ2rbxGfFl9lEM6jNfMhDzDSI4N1PNSClcu0XSSjEPp25f5rq7uqSHZ3MCRtBeAE72jfw5kcaZ2Z3q2uc9wENl1+YLKLWliV6uHNVlJZyeGrWxSVa0JseGJyY9plmFWoNjb0x+auNZczZt84Onw6X6Hs1FMRE2VF1E9p8tbLm0OSRk4F3IuT+Mxurb3YcOT+aoub4lE+b18W8rL4q5wV0UtB4vf2R1NI6xREkNnn/0CunH48g5bxf52zN2buqQG5CiT9qV+v+TgUQ7af9Mei0YSkDe4Ql6q9n88sJQ3BXLu2DdpCqCEAWaiC1jsNhO2US+9e4HUr0VAD6rB1c4HHT4/gPj+D1TE057/SmyuNTgrgp2LQi0oriGTny3F4r6xB0Z7yOG7vqwE31yWwWyMonSQf2WOwhmGVNaggtYBU3SVAofXiRt26rimiu4S1ckRg09AMzFRQceTRX6wofEpwoB4hadZ1RU8Awg85ppix8qxNxxM2p5J+5ylYI0OcuPHXNLAnrb5UUK/I7f0YZYecF7+jqKG9YTn00uaM2SNDWNarhnQkSPxHw5wV8FGI9s2AwuE/RZ1FTHfNlb3iThU9pSQ2allG449jTBgeLgAHYkPJA=
